version: "3.9"

services:
  mysql:
    container_name: mysql8.4
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"