version: "3.9"

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - ./data:/data
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"


